{
 "title": "gpbackup Exporter Dashboard",
 "description": "Dashboard works with gpbackup_exporter",
 "tags": [
  "greenplum",
  "backups",
  "gpbackup"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "database_name",
    "label": "database_name",
    "query": {
     "query": "label_values(gpbackup_backup_info,database_name)"
    }
   },
   {
    "name": "backup_type",
    "label": "backup_type",
    "query": {
     "query": "label_values(gpbackup_backup_info{database_name=~\"$database_name\"},backup_type)"
    }
   },
   {
    "name": "object_filtering",
    "label": "object_filtering",
    "query": {
     "query": "label_values(gpbackup_backup_info{database_name=~\"$database_name\", backup_type=~\"$backup_type\"},object_filtering)"
    }
   },
   {
    "name": "plugin",
    "label": "plugin",
    "query": {
     "query": "label_values(gpbackup_backup_info{database_name=~\"$database_name\", backup_type=~\"$backup_type\", object_filtering=~\"$object_filtering\"},plugin)"
    }
   },
   {
    "name": "timestamp",
    "label": "timestamp",
    "query": {
     "query": "label_values(gpbackup_backup_info{database_name=~\"$database_name\", backup_type=~\"$backup_type\", object_filtering=~\"$object_filtering\", plugin=~\"$plugin\"},timestamp)"
    }
   }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Databases",
   "type": "stat",
   "description": "Count of selected databases.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (greenplum_cluster, database_name) (gpbackup_backup_status{database_name=~\"$database_name\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sucsessful backups",
   "type": "stat",
   "description": "Count of sucsessful selected backups.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\"}==0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "stat",
   "description": "Count of failed backups.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\"} == 1))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful backups",
   "type": "timeseries",
   "description": "Count of successful selected backups.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "count by (backup_type, database_name) (avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\"} == 0))",
     "legendFormat": "{{database_name}} {{backup_type}}"
    }
   ]
  },
  {
   "title": "Sucsessful full ",
   "type": "stat",
   "description": "Count of sucsessful full backups.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\", backup_type=~\"full\"} == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sucsessful metadata-only",
   "type": "stat",
   "description": "Count of sucsessful  metadata-only backups.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\", backup_type=~\"metadata-only\"} == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sucsessful incremental ",
   "type": "stat",
   "description": "Count of sucsessful  incremental backups.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\", backup_type=~\"incremental\"} == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful data-only",
   "type": "stat",
   "description": "Count of successful data-only backups.",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\", backup_type=~\"data-only\"} == 0))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Last backups",
   "type": "table",
   "description": "Last backup status info.",
   "gridPos": { "h": 11, "w": 16, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg by (database_name) (gpbackup_backup_since_last_completion_seconds{database_name=~\"$database_name\", backup_type=\"full\"})"
    },
    {
     "expr": "avg by (database_name) (gpbackup_backup_since_last_completion_seconds{database_name=~\"$database_name\", backup_type=\"incremental\"})"
    },
    {
     "expr": "avg by (database_name) (gpbackup_backup_since_last_completion_seconds{database_name=~\"$database_name\", backup_type=\"metadata-only\"})"
    },
    {
     "expr": "avg by (database_name) (gpbackup_backup_since_last_completion_seconds{database_name=~\"$database_name\", backup_type=\"data-only\"})"
    }
   ]
  },
  {
   "title": "Failed backups",
   "type": "timeseries",
   "description": "Count of failed selected backups.",
   "gridPos": { "h": 11, "w": 8, "x": 16, "y": 13 },
   "targets": [
    {
     "expr": "count by (backup_type, database_name) (avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\"} == 1))",
     "legendFormat": "{{database_name}} {{backup_type}}"
    }
   ]
  },
  { "title": "Backup info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Backup status and duration",
   "type": "table",
   "description": "Backup status info and duration.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_status{database_name=~\"$database_name\", backup_type=~\"$backup_type\", object_filtering=~\"$object_filtering\", plugin=~\"$plugin\", timestamp=~\"$timestamp\"})"
    },
    {
     "expr": "avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_duration_seconds{database_name=~\"$database_name\", backup_type=~\"$backup_type\", object_filtering=~\"$object_filtering\", plugin=~\"$plugin\", timestamp=~\"$timestamp\"})"
    },
    {
     "expr": "avg by (backup_type, database_name, object_filtering, plugin, timestamp) (gpbackup_backup_deletion_status{database_name=~\"$database_name\", backup_type=~\"$backup_type\", object_filtering=~\"$object_filtering\", plugin=~\"$plugin\", timestamp=~\"$timestamp\"})"
    }
   ]
  },
  {
   "title": "Detailed backup info",
   "type": "table",
   "description": "Detailed backup status info.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "avg by (backup_dir, backup_ver, backup_type, compression_type, database_name, database_ver, object_filtering, plugin, plugin_ver, timestamp, with_statistic) (gpbackup_backup_info{database_name=~\"$database_name\", backup_type=~\"$backup_type\", object_filtering=~\"$object_filtering\", plugin=~\"$plugin\", timestamp=~\"$timestamp\"})"
    }
   ]
  }
 ]
}